-- MySQL Script generated by MySQL Workbench
-- Mon Sep  9 18:10:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecrpe
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecrpe` ;

-- -----------------------------------------------------
-- Schema ecrpe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecrpe` DEFAULT CHARACTER SET utf8 ;
USE `ecrpe` ;

-- -----------------------------------------------------
-- Table `ecrpe`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecrpe`.`users` ;

CREATE TABLE IF NOT EXISTS `ecrpe`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(30) NOT NULL,
  `phone_number` VARCHAR(10) NULL DEFAULT NULL,
  `email` VARCHAR(200) NOT NULL,
  `encrypted_pwd` VARCHAR(255) NOT NULL DEFAULT 'ceux_qui_ont_deja_paye',
  `is_teacher` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `email_INDEX` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `teacher_INDEX` (`is_teacher` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecrpe`.`subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecrpe`.`subjects` ;

CREATE TABLE IF NOT EXISTS `ecrpe`.`subjects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecrpe`.`refresher_courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecrpe`.`refresher_courses` ;

CREATE TABLE IF NOT EXISTS `ecrpe`.`refresher_courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `year` VARCHAR(10) NOT NULL,
  `is_finished` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `year_UNIQUE` (`year` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecrpe`.`sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecrpe`.`sessions` ;

CREATE TABLE IF NOT EXISTS `ecrpe`.`sessions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `type` ENUM('lesson', 'exercise') NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `part` SMALLINT NOT NULL,
  `recorded_on` DATE NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `refresher_course_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `refresher_course_id_idx` (`refresher_course_id` ASC) VISIBLE,
  INDEX `type_idx` (`type` ASC) VISIBLE,
  CONSTRAINT `fk_refresher_course_id`
    FOREIGN KEY (`refresher_course_id`)
    REFERENCES `ecrpe`.`refresher_courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecrpe`.`users_refresher_courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecrpe`.`users_refresher_courses` ;

CREATE TABLE IF NOT EXISTS `ecrpe`.`users_refresher_courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `refresher_course_id` INT NULL DEFAULT NULL,
  INDEX `refresher_course_id_idx` (`refresher_course_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `urc_unique` (`user_id` ASC, `refresher_course_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_urc_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecrpe`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_urc_refresher_course_id`
    FOREIGN KEY (`refresher_course_id`)
    REFERENCES `ecrpe`.`refresher_courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecrpe`.`subjects_refresher_courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecrpe`.`subjects_refresher_courses` ;

CREATE TABLE IF NOT EXISTS `ecrpe`.`subjects_refresher_courses` (
  `subject_id` INT NULL DEFAULT NULL,
  `refresher_course_id` INT NULL DEFAULT NULL,
  INDEX `subject_id_idx` (`subject_id` ASC) VISIBLE,
  INDEX `refresher_course_id_idx` (`refresher_course_id` ASC) VISIBLE,
  UNIQUE INDEX `src_unique` (`subject_id` ASC, `refresher_course_id` ASC) VISIBLE,
  CONSTRAINT `fk_src_subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `ecrpe`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_src_refresher_course_id`
    FOREIGN KEY (`refresher_course_id`)
    REFERENCES `ecrpe`.`refresher_courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecrpe`.`videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecrpe`.`videos` ;

CREATE TABLE IF NOT EXISTS `ecrpe`.`videos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NOT NULL,
  `path` VARCHAR(255) NULL DEFAULT NULL,
  `duration` VARCHAR(50) NULL DEFAULT NULL,
  `is_encoded` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `path_UNIQUE` (`path` ASC) VISIBLE,
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `is_encoded_Idx` (`is_encoded` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecrpe`.`sessions_videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecrpe`.`sessions_videos` ;

CREATE TABLE IF NOT EXISTS `ecrpe`.`sessions_videos` (
  `session_id` INT NULL DEFAULT NULL,
  `video_id` INT NULL DEFAULT NULL,
  INDEX `session_id_idx` (`session_id` ASC) VISIBLE,
  INDEX `video_id_idx` (`video_id` ASC) VISIBLE,
  UNIQUE INDEX `sv_unique` (`session_id` ASC, `video_id` ASC) VISIBLE,
  CONSTRAINT `fk_session_id`
    FOREIGN KEY (`session_id`)
    REFERENCES `ecrpe`.`sessions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_id`
    FOREIGN KEY (`video_id`)
    REFERENCES `ecrpe`.`videos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecrpe`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecrpe`.`payments` ;

CREATE TABLE IF NOT EXISTS `ecrpe`.`payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecrpe`.`users_refresher_courses_payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecrpe`.`users_refresher_courses_payments` ;

CREATE TABLE IF NOT EXISTS `ecrpe`.`users_refresher_courses_payments` (
  `payment_id` INT NULL DEFAULT NULL,
  `user_refresher_course_id` INT NULL DEFAULT NULL,
  INDEX `payment_id` (`payment_id` ASC) VISIBLE,
  INDEX `user_refresher_course_id` (`user_refresher_course_id` ASC) VISIBLE,
  UNIQUE INDEX `uscp_UNIQUE` (`user_refresher_course_id` ASC, `payment_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_id`
    FOREIGN KEY (`payment_id`)
    REFERENCES `ecrpe`.`payments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_refresher_course_id`
    FOREIGN KEY (`user_refresher_course_id`)
    REFERENCES `ecrpe`.`users_refresher_courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecrpe`.`user_auths`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecrpe`.`user_auths` ;

CREATE TABLE IF NOT EXISTS `ecrpe`.`user_auths` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(45) NOT NULL,
  `refresh_token` VARCHAR(255) NOT NULL,
  `delivered_at` DATETIME NOT NULL,
  `is_revoked` TINYINT NOT NULL DEFAULT 0,
  `revoked_at` DATETIME NULL,
  `on_login` TINYINT NOT NULL DEFAULT 0,
  `on_refresh` TINYINT NOT NULL DEFAULT 0,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `refresh_token_UNIQUE` (`refresh_token` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecrpe`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
