// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen

type NewUser struct {
	Username    string  `json:"username"`
	PhoneNumber *string `json:"phoneNumber"`
	Email       string  `json:"email"`
	CurrentRank *int    `json:"currentRank"`
}

type UpdatedUser struct {
	Username    string  `json:"username"`
	PhoneNumber *string `json:"phoneNumber"`
	Email       *string `json:"email"`
	CurrentRank *int    `json:"currentRank"`
}

type UserLogin struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
